<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Final Techfios Project" duration-ms="21912" started-at="2021-11-19T19:28:49Z" finished-at="2021-11-19T19:29:11Z">
    <groups>
    </groups>
    <test name="Testcasepractice" duration-ms="21912" started-at="2021-11-19T19:28:49Z" finished-at="2021-11-19T19:29:11Z">
      <class name="test.AddCategoryTest">
        <test-method status="PASS" signature="validUserShouldBeAbleToAddCategory(java.lang.String)[pri:0, instance:test.AddCategoryTest@28d25987]" name="validUserShouldBeAbleToAddCategory" duration-ms="10677" started-at="2021-11-19T19:28:49Z" finished-at="2021-11-19T19:29:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[grocery]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserShouldBeAbleToAddCategory -->
        <test-method status="PASS" signature="validateAllMonthsPresentInTheDropDown()[pri:0, instance:test.AddCategoryTest@28d25987]" name="validateAllMonthsPresentInTheDropDown" duration-ms="4671" started-at="2021-11-19T19:29:00Z" finished-at="2021-11-19T19:29:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAllMonthsPresentInTheDropDown -->
        <test-method status="FAIL" signature="validatingOnlyUniqueOrdersCanBeAdded(java.lang.String)[pri:0, instance:test.AddCategoryTest@28d25987]" name="validatingOnlyUniqueOrdersCanBeAdded" duration-ms="6535" started-at="2021-11-19T19:29:05Z" finished-at="2021-11-19T19:29:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[grocery]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Duplicate category not allowed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Duplicate category not allowed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at test.AddCategoryTest.validatingOnlyUniqueOrdersCanBeAdded(AddCategoryTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatingOnlyUniqueOrdersCanBeAdded -->
      </class> <!-- test.AddCategoryTest -->
    </test> <!-- Testcasepractice -->
  </suite> <!-- Final Techfios Project -->
</testng-results>
